# Install Dependencies

In [ ]:
!pip install -q transformers==4.45.2
!pip install -q tokenizers==0.20.1
!pip install -q sentencepiece==0.2.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 139.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 64.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 181.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 66.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 30.2 MB/s eta 0:00:00

In [ ]:
!pip install -q arabert

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.0/185.0 kB 8.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 18.4 MB/s eta 0:00:00
  Building wheel for emoji (setup.py) ... done

# News Classification

In [ ]:
!unzip "/content/Sanad/Arabiya.zip" -d "/content/Sanad/Arabiya"
!unzip "/content/Sanad/Khaleej.zip" -d "/content/Sanad/Khaleej"
!unzip "/content/Sanad/Akhbarona.zip" -d "/content/Sanad/Akhbarona"

Streaming output truncated to the last 5000 lines.
  inflating: /content/Sanad/Akhbarona/Tech/02392.txt
  inflating: /content/Sanad/Akhbarona/Tech/02435.txt
  inflating: /content/Sanad/Akhbarona/Tech/02437.txt
  inflating: /content/Sanad/Akhbarona/Tech/02458.txt
  inflating: /content/Sanad/Akhbarona/Tech/02468.txt
  inflating: /content/Sanad/Akhbarona/Tech/02469.txt
  inflating: /content/Sanad/Akhbarona/Tech/02479.txt
  inflating: /content/Sanad/Akhbarona/Tech/02490.txt
  inflating: /content/Sanad/Akhbarona/Tech/02492.txt
  inflating: /content/Sanad/Akhbarona/Tech/02521.txt
  inflating: /content/Sanad/Akhbarona/Tech/02539.txt
  inflating: /content/Sanad/Akhbarona/Tech/02542.txt
  inflating: /content/Sanad/Akhbarona/Tech/02548.txt
  inflating: /content/Sanad/Akhbarona/Tech/02558.txt
  inflating: /content/Sanad/Akhbarona/Tech/02581.txt
  inflating: /content/Sanad/Akhbarona/Tech/02583.txt
  inflating: /content/Sanad/Akhbarona/Tech/02585.txt
  inflating: /content/Sanad/Akhbarona/Tech/02586.txt
  inflating: /content/Sanad/Akhbarona/Tech/02589.txt
  inflating: /content/Sanad/Akhbarona/Tech/02606.txt
  inflating: /content/Sanad/Akhbarona/Tech/02611.txt
  inflating: /content/Sanad/Akhbarona/Tech/02632.txt
  inflating: /content/Sanad/Akhbarona/Tech/02644.txt
  inflating: /content/Sanad/Akhbarona/Tech/02652.txt
  inflating: /content/Sanad/Akhbarona/Tech/02663.txt
  inflating: /content/Sanad/Akhbarona/Tech/02666.txt
  inflating: /content/Sanad/Akhbarona/Tech/02683.txt
  inflating: /content/Sanad/Akhbarona/Tech/02684.txt
  inflating: /content/Sanad/Akhbarona/Tech/02705.txt
  inflating: /content/Sanad/Akhbarona/Tech/02713.txt
  inflating: /content/Sanad/Akhbarona/Tech/02718.txt
  inflating: /content/Sanad/Akhbarona/Tech/02729.txt
  inflating: /content/Sanad/Akhbarona/Tech/02750.txt
  inflating: /content/Sanad/Akhbarona/Tech/02753.txt
  inflating: /content/Sanad/Akhbarona/Tech/02765.txt
  inflating: /content/Sanad/Akhbarona/Tech/02779.txt
  inflating: /content/Sanad/Akhbarona/Tech/02788.txt
  inflating: /content/Sanad/Akhbarona/Tech/02789.txt
  inflating: /content/Sanad/Akhbarona/Tech/02791.txt
  inflating: /content/Sanad/Akhbarona/Tech/02798.txt
  inflating: /content/Sanad/Akhbarona/Tech/02836.txt
  inflating: /content/Sanad/Akhbarona/Tech/02852.txt
  inflating: /content/Sanad/Akhbarona/Tech/02864.txt
  inflating: /content/Sanad/Akhbarona/Tech/02889.txt
  inflating: /content/Sanad/Akhbarona/Tech/02891.txt
  inflating: /content/Sanad/Akhbarona/Tech/02918.txt
  inflating: /content/Sanad/Akhbarona/Tech/02922.txt
  inflating: /content/Sanad/Akhbarona/Tech/02929.txt
  inflating: /content/Sanad/Akhbarona/Tech/02938.txt
  inflating: /content/Sanad/Akhbarona/Tech/02946.txt
  inflating: /content/Sanad/Akhbarona/Tech/02953.txt
  inflating: /content/Sanad/Akhbarona/Tech/02959.txt
  inflating: /content/Sanad/Akhbarona/Tech/02974.txt
  inflating: /content/Sanad/Akhbarona/Tech/03005.txt
  inflating: /content/Sanad/Akhbarona/Tech/03011.txt
  inflating: /content/Sanad/Akhbarona/Tech/03012.txt
  inflating: /content/Sanad/Akhbarona/Tech/03013.txt
  inflating: /content/Sanad/Akhbarona/Tech/03067.txt
  inflating: /content/Sanad/Akhbarona/Tech/03078.txt
  inflating: /content/Sanad/Akhbarona/Tech/03083.txt
  inflating: /content/Sanad/Akhbarona/Tech/03094.txt
  inflating: /content/Sanad/Akhbarona/Tech/03103.txt
  inflating: /content/Sanad/Akhbarona/Tech/03138.txt
  inflating: /content/Sanad/Akhbarona/Tech/03242.txt
  inflating: /content/Sanad/Akhbarona/Tech/03247.txt
  inflating: /content/Sanad/Akhbarona/Tech/03248.txt
  inflating: /content/Sanad/Akhbarona/Tech/03250.txt
  inflating: /content/Sanad/Akhbarona/Tech/03254.txt
  inflating: /content/Sanad/Akhbarona/Tech/03268.txt
  inflating: /content/Sanad/Akhbarona/Tech/03286.txt
  inflating: /content/Sanad/Akhbarona/Tech/03299.txt
  inflating: /content/Sanad/Akhbarona/Tech/03309.txt
  inflating: /content/Sanad/Akhbarona/Tech/03311.txt
  inflating: /content/Sanad/Akhbarona/Tech/03323.txt
  inflating: /content/Sanad/Akhbarona/Tech/03338.txt
  inflating: /content/Sanad/Akhbarona/Tech/03356.txt
  inflating: /content/Sanad/Akhbarona/Tech/03359.txt
  inflating: /content/Sanad/Akhbarona/Tech/03362.txt
  inflating: /content/Sanad/Akhbarona/Tech/03377.txt
  inflating: /content/Sanad/Akhbarona/Tech/03380.txt
  inflating: /content/Sanad/Akhbarona/Tech/03393.txt
  inflating: /content/Sanad/Akhbarona/Tech/03430.txt
  inflating: /content/Sanad/Akhbarona/Tech/03439.txt
  inflating: /content/Sanad/Akhbarona/Tech/03453.txt
  inflating: /content/Sanad/Akhbarona/Tech/03454.txt
  inflating: /content/Sanad/Akhbarona/Tech/03467.txt
  inflating: /content/Sanad/Akhbarona/Tech/03479.txt
  inflating: /content/Sanad/Akhbarona/Tech/03490.txt
  inflating: /content/Sanad/Akhbarona/Tech/03509.txt
  inflating: /content/Sanad/Akhbarona/Tech/03513.txt
  inflating: /content/Sanad/Akhbarona/Tech/03530.txt
  inflating: /content/Sanad/Akhbarona/Tech/03535.txt
  inflating: /content/Sanad/Akhbarona/Tech/03541.txt
  inflating: /content/Sanad/Akhbarona/Tech/03581.txt
  inflating: /content/Sanad/Akhbarona/Tech/03582.txt
  inflating: /content/Sanad/Akhbarona/Tech/03583.txt
  inflating: /content/Sanad/Akhbarona/Tech/03586.txt
  inflating: /content/Sanad/Akhbarona/Tech/03598.txt
  inflating: /content/Sanad/Akhbarona/Tech/03600.txt
  inflating: /content/Sanad/Akhbarona/Tech/03614.txt
  inflating: /content/Sanad/Akhbarona/Tech/03642.txt
  inflating: /content/Sanad/Akhbarona/Tech/03651.txt
  inflating: /content/Sanad/Akhbarona/Tech/03696.txt
  inflating: /content/Sanad/Akhbarona/Tech/03709.txt
  inflating: /content/Sanad/Akhbarona/Tech/03713.txt
  inflating: /content/Sanad/Akhbarona/Tech/03733.txt
  inflating: /content/Sanad/Akhbarona/Tech/03747.txt
  inflating: /content/Sanad/Akhbarona/Tech/03750.txt
  inflating: /content/Sanad/Akhbarona/Tech/03763.txt
  inflating: /content/Sanad/Akhbarona/Tech/03782.txt
  inflating: /content/Sanad/Akhbarona/Tech/03796.txt
  inflating: /content/Sanad/Akhbarona/Tech/03805.txt
  inflating: /content/Sanad/Akhbarona/Tech/03808.txt
  inflating: /content/Sanad/Akhbarona/Tech/03818.txt
  inflating: /content/Sanad/Akhbarona/Tech/03822.txt
  inflating: /content/Sanad/Akhbarona/Tech/03825.txt
  inflating: /content/Sanad/Akhbarona/Tech/03864.txt
  inflating: /content/Sanad/Akhbarona/Tech/03879.txt
  inflating: /content/Sanad/Akhbarona/Tech/03880.txt
  inflating: /content/Sanad/Akhbarona/Tech/03887.txt
  inflating: /content/Sanad/Akhbarona/Tech/03904.txt
  inflating: /content/Sanad/Akhbarona/Tech/03918.txt
  inflating: /content/Sanad/Akhbarona/Tech/03942.txt
  inflating: /content/Sanad/Akhbarona/Tech/03980.txt
  inflating: /content/Sanad/Akhbarona/Tech/03993.txt
  inflating: /content/Sanad/Akhbarona/Tech/04019.txt
  inflating: /content/Sanad/Akhbarona/Tech/04024.txt
  inflating: /content/Sanad/Akhbarona/Tech/04026.txt
  inflating: /content/Sanad/Akhbarona/Tech/04028.txt
  inflating: /content/Sanad/Akhbarona/Tech/04034.txt
  inflating: /content/Sanad/Akhbarona/Tech/04043.txt
  inflating: /content/Sanad/Akhbarona/Tech/04063.txt
  inflating: /content/Sanad/Akhbarona/Tech/04072.txt
  inflating: /content/Sanad/Akhbarona/Tech/04073.txt
  inflating: /content/Sanad/Akhbarona/Tech/04094.txt
  inflating: /content/Sanad/Akhbarona/Tech/04147.txt
  inflating: /content/Sanad/Akhbarona/Tech/04156.txt
  inflating: /content/Sanad/Akhbarona/Tech/04168.txt
  inflating: /content/Sanad/Akhbarona/Tech/04171.txt
  inflating: /content/Sanad/Akhbarona/Tech/04176.txt
  inflating: /content/Sanad/Akhbarona/Tech/04185.txt
  inflating: /content/Sanad/Akhbarona/Tech/04186.txt
  inflating: /content/Sanad/Akhbarona/Tech/04233.txt
  inflating: /content/Sanad/Akhbarona/Tech/04235.txt
  inflating: /content/Sanad/Akhbarona/Tech/04237.txt
  inflating: /content/Sanad/Akhbarona/Tech/04241.txt
  inflating: /content/Sanad/Akhbarona/Tech/04242.txt
  inflating: /content/Sanad/Akhbarona/Tech/04256.txt
  inflating: /content/Sanad/Akhbarona/Tech/04257.txt
  inflating: /content/Sanad/Akhbarona/Tech/04275.txt
  inflating: /content/Sanad/Akhbarona/Tech/04278.txt
  inflating: /content/Sanad/Akhbarona/Tech/04290.txt
  inflating: /content/Sanad/Akhbarona/Tech/04293.txt
  inflating: /content/Sanad/Akhbarona/Tech/04297.txt
  inflating: /content/Sanad/Akhbarona/Tech/04325.txt
  inflating: /content/Sanad/Akhbarona/Tech/04337.txt
  inflating: /content/Sanad/Akhbarona/Tech/04353.txt
  inflating: /content/Sanad/Akhbarona/Tech/04356.txt
  inflating: /content/Sanad/Akhbarona/Tech/04364.txt
  inflating: /content/Sanad/Akhbarona/Tech/04366.txt
  inflating: /content/Sanad/Akhbarona/Tech/04368.txt
  inflating: /content/Sanad/Akhbarona/Tech/04378.txt
  inflating: /content/Sanad/Akhbarona/Tech/04405.txt
  inflating: /content/Sanad/Akhbarona/Tech/04417.txt
  inflating: /content/Sanad/Akhbarona/Tech/04435.txt
  inflating: /content/Sanad/Akhbarona/Tech/04454.txt
  inflating: /content/Sanad/Akhbarona/Tech/04484.txt
  inflating: /content/Sanad/Akhbarona/Tech/04494.txt
  inflating: /content/Sanad/Akhbarona/Tech/04502.txt
  inflating: /content/Sanad/Akhbarona/Tech/04507.txt
  inflating: /content/Sanad/Akhbarona/Tech/04514.txt
  inflating: /content/Sanad/Akhbarona/Tech/04524.txt
  inflating: /content/Sanad/Akhbarona/Tech/04544.txt
  inflating: /content/Sanad/Akhbarona/Tech/04552.txt
  inflating: /content/Sanad/Akhbarona/Tech/04563.txt
  inflating: /content/Sanad/Akhbarona/Tech/04597.txt
  inflating: /content/Sanad/Akhbarona/Tech/04609.txt
  inflating: /content/Sanad/Akhbarona/Tech/04618.txt
  inflating: /content/Sanad/Akhbarona/Tech/04632.txt
  inflating: /content/Sanad/Akhbarona/Tech/04636.txt
  inflating: /content/Sanad/Akhbarona/Tech/04637.txt
  inflating: /content/Sanad/Akhbarona/Tech/04640.txt
  inflating: /content/Sanad/Akhbarona/Tech/04647.txt
  inflating: /content/Sanad/Akhbarona/Tech/04666.txt
  inflating: /content/Sanad/Akhbarona/Tech/04668.txt
  inflating: /content/Sanad/Akhbarona/Tech/04691.txt
  inflating: /content/Sanad/Akhbarona/Tech/04692.txt
  inflating: /content/Sanad/Akhbarona/Tech/04705.txt
  inflating: /content/Sanad/Akhbarona/Tech/04718.txt
  inflating: /content/Sanad/Akhbarona/Tech/04721.txt
  inflating: /content/Sanad/Akhbarona/Tech/04731.txt
  inflating: /content/Sanad/Akhbarona/Tech/04733.txt
  inflating: /content/Sanad/Akhbarona/Tech/04741.txt
  inflating: /content/Sanad/Akhbarona/Tech/04767.txt
  inflating: /content/Sanad/Akhbarona/Tech/04785.txt
  inflating: /content/Sanad/Akhbarona/Tech/04788.txt
  inflating: /content/Sanad/Akhbarona/Tech/04791.txt
  inflating: /content/Sanad/Akhbarona/Tech/04799.txt
  inflating: /content/Sanad/Akhbarona/Tech/04801.txt
  inflating: /content/Sanad/Akhbarona/Tech/04802.txt
  inflating: /content/Sanad/Akhbarona/Tech/04813.txt
  inflating: /content/Sanad/Akhbarona/Tech/04845.txt
  inflating: /content/Sanad/Akhbarona/Tech/04858.txt
  inflating: /content/Sanad/Akhbarona/Tech/04859.txt
  inflating: /content/Sanad/Akhbarona/Tech/04860.txt
  inflating: /content/Sanad/Akhbarona/Tech/04866.txt
  inflating: /content/Sanad/Akhbarona/Tech/04912.txt
  inflating: /content/Sanad/Akhbarona/Tech/04923.txt
  inflating: /content/Sanad/Akhbarona/Tech/04931.txt
  inflating: /content/Sanad/Akhbarona/Tech/04946.txt
  inflating: /content/Sanad/Akhbarona/Tech/04947.txt
  inflating: /content/Sanad/Akhbarona/Tech/04974.txt
  inflating: /content/Sanad/Akhbarona/Tech/04977.txt
  inflating: /content/Sanad/Akhbarona/Tech/04985.txt
  inflating: /content/Sanad/Akhbarona/Tech/04986.txt
  inflating: /content/Sanad/Akhbarona/Tech/05008.txt
  inflating: /content/Sanad/Akhbarona/Tech/05014.txt
  inflating: /content/Sanad/Akhbarona/Tech/05045.txt
  inflating: /content/Sanad/Akhbarona/Tech/05048.txt
  inflating: /content/Sanad/Akhbarona/Tech/05061.txt
  inflating: /content/Sanad/Akhbarona/Tech/05066.txt
  inflating: /content/Sanad/Akhbarona/Tech/05076.txt
  inflating: /content/Sanad/Akhbarona/Tech/05078.txt
  inflating: /content/Sanad/Akhbarona/Tech/05087.txt
  inflating: /content/Sanad/Akhbarona/Tech/05104.txt
  inflating: /content/Sanad/Akhbarona/Tech/05111.txt
  inflating: /content/Sanad/Akhbarona/Tech/05113.txt
  inflating: /content/Sanad/Akhbarona/Tech/05135.txt
  inflating: /content/Sanad/Akhbarona/Tech/05149.txt
  inflating: /content/Sanad/Akhbarona/Tech/05170.txt
  inflating: /content/Sanad/Akhbarona/Tech/05174.txt
  inflating: /content/Sanad/Akhbarona/Tech/05181.txt
  inflating: /content/Sanad/Akhbarona/Tech/05191.txt
  inflating: /content/Sanad/Akhbarona/Tech/05194.txt
  inflating: /content/Sanad/Akhbarona/Tech/05217.txt
  inflating: /content/Sanad/Akhbarona/Tech/05224.txt
  inflating: /content/Sanad/Akhbarona/Tech/05234.txt
  inflating: /content/Sanad/Akhbarona/Tech/05243.txt
  inflating: /content/Sanad/Akhbarona/Tech/05254.txt
  inflating: /content/Sanad/Akhbarona/Tech/05270.txt
  inflating: /content/Sanad/Akhbarona/Tech/05278.txt
  inflating: /content/Sanad/Akhbarona/Tech/05280.txt
  inflating: /content/Sanad/Akhbarona/Tech/05319.txt
  inflating: /content/Sanad/Akhbarona/Tech/05328.txt
  inflating: /content/Sanad/Akhbarona/Tech/05335.txt
  inflating: /content/Sanad/Akhbarona/Tech/05337.txt
  inflating: /content/Sanad/Akhbarona/Tech/05345.txt
  inflating: /content/Sanad/Akhbarona/Tech/05362.txt
  inflating: /content/Sanad/Akhbarona/Tech/05371.txt
  inflating: /content/Sanad/Akhbarona/Tech/05383.txt
  inflating: /content/Sanad/Akhbarona/Tech/05408.txt
  inflating: /content/Sanad/Akhbarona/Tech/05420.txt
  inflating: /content/Sanad/Akhbarona/Tech/05427.txt
  inflating: /content/Sanad/Akhbarona/Tech/05437.txt
  inflating: /content/Sanad/Akhbarona/Tech/05447.txt
  inflating: /content/Sanad/Akhbarona/Tech/05454.txt
  inflating: /content/Sanad/Akhbarona/Tech/05474.txt
  inflating: /content/Sanad/Akhbarona/Tech/05476.txt
  inflating: /content/Sanad/Akhbarona/Tech/05477.txt
  inflating: /content/Sanad/Akhbarona/Tech/05478.txt
  inflating: /content/Sanad/Akhbarona/Tech/05506.txt
  inflating: /content/Sanad/Akhbarona/Tech/05507.txt
  inflating: /content/Sanad/Akhbarona/Tech/05523.txt
  inflating: /content/Sanad/Akhbarona/Tech/05526.txt
  inflating: /content/Sanad/Akhbarona/Tech/05538.txt
  inflating: /content/Sanad/Akhbarona/Tech/05542.txt
  inflating: /content/Sanad/Akhbarona/Tech/05547.txt
  inflating: /content/Sanad/Akhbarona/Tech/05562.txt
  inflating: /content/Sanad/Akhbarona/Tech/05563.txt
  inflating: /content/Sanad/Akhbarona/Tech/05568.txt
  inflating: /content/Sanad/Akhbarona/Tech/05598.txt
  inflating: /content/Sanad/Akhbarona/Tech/05625.txt
  inflating: /content/Sanad/Akhbarona/Tech/05627.txt
  inflating: /content/Sanad/Akhbarona/Tech/05643.txt
  inflating: /content/Sanad/Akhbarona/Tech/05644.txt
  inflating: /content/Sanad/Akhbarona/Tech/05675.txt
  inflating: /content/Sanad/Akhbarona/Tech/05683.txt
  inflating: /content/Sanad/Akhbarona/Tech/05688.txt
  inflating: /content/Sanad/Akhbarona/Tech/05690.txt
  inflating: /content/Sanad/Akhbarona/Tech/05696.txt
  inflating: /content/Sanad/Akhbarona/Tech/05702.txt
  inflating: /content/Sanad/Akhbarona/Tech/05703.txt
  inflating: /content/Sanad/Akhbarona/Tech/05713.txt
  inflating: /content/Sanad/Akhbarona/Tech/05714.txt
  inflating: /content/Sanad/Akhbarona/Tech/05726.txt
  inflating: /content/Sanad/Akhbarona/Tech/05729.txt
  inflating: /content/Sanad/Akhbarona/Tech/05734.txt
  inflating: /content/Sanad/Akhbarona/Tech/05759.txt
  inflating: /content/Sanad/Akhbarona/Tech/05799.txt
  inflating: /content/Sanad/Akhbarona/Tech/05802.txt
  inflating: /content/Sanad/Akhbarona/Tech/05807.txt
  inflating: /content/Sanad/Akhbarona/Tech/05817.txt
  inflating: /content/Sanad/Akhbarona/Tech/05849.txt
  inflating: /content/Sanad/Akhbarona/Tech/05873.txt
  inflating: /content/Sanad/Akhbarona/Tech/05882.txt
  inflating: /content/Sanad/Akhbarona/Tech/05895.txt
  inflating: /content/Sanad/Akhbarona/Tech/05906.txt
  inflating: /content/Sanad/Akhbarona/Tech/05913.txt
  inflating: /content/Sanad/Akhbarona/Tech/05915.txt
  inflating: /content/Sanad/Akhbarona/Tech/05937.txt
  inflating: /content/Sanad/Akhbarona/Tech/05947.txt
  inflating: /content/Sanad/Akhbarona/Tech/05965.txt
  inflating: /content/Sanad/Akhbarona/Tech/05990.txt
  inflating: /content/Sanad/Akhbarona/Tech/05994.txt
  inflating: /content/Sanad/Akhbarona/Tech/06006.txt
  inflating: /content/Sanad/Akhbarona/Tech/06020.txt
  inflating: /content/Sanad/Akhbarona/Tech/06022.txt
  inflating: /content/Sanad/Akhbarona/Tech/06046.txt
  inflating: /content/Sanad/Akhbarona/Tech/06049.txt
  inflating: /content/Sanad/Akhbarona/Tech/06057.txt
  inflating: /content/Sanad/Akhbarona/Tech/06063.txt
  inflating: /content/Sanad/Akhbarona/Tech/06066.txt
  inflating: /content/Sanad/Akhbarona/Tech/06087.txt
  inflating: /content/Sanad/Akhbarona/Tech/06093.txt
  inflating: /content/Sanad/Akhbarona/Tech/06104.txt
  inflating: /content/Sanad/Akhbarona/Tech/06163.txt
  inflating: /content/Sanad/Akhbarona/Tech/06170.txt
  inflating: /content/Sanad/Akhbarona/Tech/06173.txt
  inflating: /content/Sanad/Akhbarona/Tech/06184.txt
  inflating: /content/Sanad/Akhbarona/Tech/06188.txt
  inflating: /content/Sanad/Akhbarona/Tech/06194.txt
  inflating: /content/Sanad/Akhbarona/Tech/06202.txt
  inflating: /content/Sanad/Akhbarona/Tech/06203.txt
  inflating: /content/Sanad/Akhbarona/Tech/06233.txt
  inflating: /content/Sanad/Akhbarona/Tech/06253.txt
  inflating: /content/Sanad/Akhbarona/Tech/06264.txt
  inflating: /content/Sanad/Akhbarona/Tech/06276.txt
  inflating: /content/Sanad/Akhbarona/Tech/06291.txt
  inflating: /content/Sanad/Akhbarona/Tech/06308.txt
  inflating: /content/Sanad/Akhbarona/Tech/06327.txt
  inflating: /content/Sanad/Akhbarona/Tech/06329.txt
  inflating: /content/Sanad/Akhbarona/Tech/06348.txt
  inflating: /content/Sanad/Akhbarona/Tech/06355.txt
  inflating: /content/Sanad/Akhbarona/Tech/06359.txt
  inflating: /content/Sanad/Akhbarona/Tech/06365.txt
  inflating: /content/Sanad/Akhbarona/Tech/06366.txt
  inflating: /content/Sanad/Akhbarona/Tech/06370.txt
  inflating: /content/Sanad/Akhbarona/Tech/06371.txt
  inflating: /content/Sanad/Akhbarona/Tech/06376.txt
  inflating: /content/Sanad/Akhbarona/Tech/06393.txt
  inflating: /content/Sanad/Akhbarona/Tech/06394.txt
  inflating: /content/Sanad/Akhbarona/Tech/06395.txt
  inflating: /content/Sanad/Akhbarona/Tech/06426.txt
  inflating: /content/Sanad/Akhbarona/Tech/06453.txt
  inflating: /content/Sanad/Akhbarona/Tech/06456.txt
  inflating: /content/Sanad/Akhbarona/Tech/06457.txt
  inflating: /content/Sanad/Akhbarona/Tech/06479.txt
  inflating: /content/Sanad/Akhbarona/Tech/06487.txt
  inflating: /content/Sanad/Akhbarona/Tech/06497.txt
  inflating: /content/Sanad/Akhbarona/Tech/06500.txt
  inflating: /content/Sanad/Akhbarona/Tech/06513.txt
  inflating: /content/Sanad/Akhbarona/Tech/06518.txt
  inflating: /content/Sanad/Akhbarona/Tech/06520.txt
  inflating: /content/Sanad/Akhbarona/Tech/06544.txt
  inflating: /content/Sanad/Akhbarona/Tech/06559.txt
  inflating: /content/Sanad/Akhbarona/Tech/06561.txt
  inflating: /content/Sanad/Akhbarona/Tech/06579.txt
  inflating: /content/Sanad/Akhbarona/Tech/06603.txt
  inflating: /content/Sanad/Akhbarona/Tech/06604.txt
  inflating: /content/Sanad/Akhbarona/Tech/06623.txt
  inflating: /content/Sanad/Akhbarona/Tech/06626.txt
  inflating: /content/Sanad/Akhbarona/Tech/06644.txt
  inflating: /content/Sanad/Akhbarona/Tech/06648.txt
  inflating: /content/Sanad/Akhbarona/Tech/06706.txt
  inflating: /content/Sanad/Akhbarona/Tech/06707.txt
  inflating: /content/Sanad/Akhbarona/Tech/06708.txt
  inflating: /content/Sanad/Akhbarona/Tech/06711.txt
  inflating: /content/Sanad/Akhbarona/Tech/06719.txt
  inflating: /content/Sanad/Akhbarona/Tech/06730.txt
  inflating: /content/Sanad/Akhbarona/Tech/06756.txt
  inflating: /content/Sanad/Akhbarona/Tech/06769.txt
  inflating: /content/Sanad/Akhbarona/Tech/06786.txt
  inflating: /content/Sanad/Akhbarona/Tech/06795.txt
  inflating: /content/Sanad/Akhbarona/Tech/06811.txt
  inflating: /content/Sanad/Akhbarona/Tech/06814.txt
  inflating: /content/Sanad/Akhbarona/Tech/06819.txt

## Load dataset

In [ ]:
import os
import pandas as pd

root_dir = "Sanad"

data = []

for directory in os.listdir(root_dir):
    directory_path = os.path.join(root_dir, directory)

    # Make sure it is a directory
    if not os.path.isdir(directory_path):
        continue

    # Each subdirectory is a news class
    for news_class in os.listdir(directory_path):
        class_path = os.path.join(directory_path, news_class)

        if not os.path.isdir(class_path):
            continue

        # Read all txt files
        for filename in os.listdir(class_path):
            if filename.endswith(".txt"):
                file_path = os.path.join(class_path, filename)

                with open(file_path, "r", encoding="utf-8") as f:
                    text = f.read()

                data.append({
                    "content": text,
                    "class": news_class,
                    "directory": directory
                })

df = pd.DataFrame(data)

print(df.shape[0])

195174

In [ ]:
df.columns

Index(['content', 'class', 'directory'], dtype='object')

In [ ]:
df.dropna(inplace = True, subset = 'content')

In [ ]:
test_samples = pd.read_excel('sampled_data-NewsClassification.xlsx')
test_samples.head(1)

,main directory,subdirectory,content
0,Khaleej,Culture,استقبل الوسط المسرحي الإماراتي فوز الإمارات بر...

In [ ]:
test_samples.shape[0]

1000

In [ ]:
data_filtered = df[~df["content"].isin(test_samples["content"])]
data_filtered .shape[0]

194149

In [ ]:
data_filtered.reset_index(drop = True, inplace = True)

# Split Data

In [ ]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(
    data_filtered, test_size=0.3,
    random_state=42, stratify = data_filtered['class']
)

dev, test = train_test_split(
    temp, test_size=0.3,
    random_state=42, stratify = temp['class']
)

train['split'] = 'train'
dev['split'] = 'dev'
test['split'] = 'test'

split_data = pd.concat([train, dev, test])

In [ ]:
from datasets import Dataset, DatasetDict

# Create datasets for each split
news = DatasetDict({
    split: Dataset.from_pandas(
        split_data[split_data["split"] == split][["content", "class"]],
        preserve_index=False
    )
    for split in ["train", "dev", "test"]
})

## Preprocess

The next step is to load a T5 tokenizer to process `text` and `summary`:

In [ ]:
from transformers import AutoTokenizer

checkpoint = "UBC-NLP/AraT5v2-base-1024"
tokenizer = AutoTokenizer.from_pretrained(
    checkpoint,
    use_fast=False
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [ ]:
prefix = "تصنيف الخبر: "


def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["content"]]
    model_inputs = tokenizer(inputs, max_length=1024, truncation=True)

    labels = tokenizer(text_target=examples["class"], max_length=128, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
tokenized_news = news.map(preprocess_function, batched=True)

Map:   0%|          | 0/135904 [00:00<?, ? examples/s]

Map:   0%|          | 0/40771 [00:00<?, ? examples/s]

Map:   0%|          | 0/17474 [00:00<?, ? examples/s]

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

## Evaluate

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_preds):

    predictions, labels = eval_preds

    decoded_predictions = tokenizer.batch_decode(
        predictions,
        skip_special_tokens=True
    )

    labels = np.where(
        labels != -100,
        labels,
        tokenizer.pad_token_id
    )

    decoded_labels = tokenizer.batch_decode(
        labels,
        skip_special_tokens=True
    )

    decoded_predictions = [
        p.strip()
        for p in decoded_predictions
    ]

    decoded_labels = [
        l.strip()
        for l in decoded_labels
    ]

    accuracy = accuracy_score(
        decoded_labels,
        decoded_predictions
    )

    f1 = f1_score(
        decoded_labels,
        decoded_predictions,
        average="macro"
    )

    return {
        "accuracy": accuracy,
        "f1": f1
    }

## Train

In [ ]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="sentiment_model",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=4,
    predict_with_generate=True,
    fp16=True,
    report_to="none"
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_news["train"],
    eval_dataset=tokenized_news["dev"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1220: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1220: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1220: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1220: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

TrainOutput(global_step=33976, training_loss=0.10515476081521197, metrics={'train_runtime': 13549.3238, 'train_samples_per_second': 40.121, 'train_steps_per_second': 2.508, 'total_flos': 8.322780340623606e+17, 'train_loss': 0.10515476081521197, 'epoch': 4.0})

## Inference

In [ ]:
text = 'لقد ضلم ماكرون الشعب المصرى وساهم في قمعه وقتله بتنسيقه مع العصابة السيسية ودعمها فانتقم الله منه https://t.co/anjidHMCzK'

In [ ]:
from transformers import AutoTokenizer
dir = 'sentiment_model/checkpoint-33976'
tokenizer = AutoTokenizer.from_pretrained(dir)
inputs = tokenizer(text, return_tensors="pt").input_ids

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers

In [ ]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained(dir)
outputs = model.generate(inputs, max_new_tokens=100, do_sample=False)

In [ ]:
tokenizer.decode(outputs[0], skip_special_tokens=True)

'Politics'

In [ ]:
sentiment = []
for text in test_samples['content']:
  inputs = tokenizer(text, return_tensors="pt").input_ids
  outputs = model.generate(inputs, max_new_tokens=100, do_sample=False)
  sentiment.append(tokenizer.decode(outputs[0], skip_special_tokens=True))

Token indices sequence length is longer than the specified maximum sequence length for this model (1095 > 1024). Running this sequence through the model will result in indexing errors

In [ ]:
test_samples['Predicted Class'] = sentiment
test_samples.to_excel('Predicted Class by AraT5.xlsx', index = False)
test_samples.head(2)

,main directory,subdirectory,content,Predicted Class
0,Khaleej,Culture,استقبل الوسط المسرحي الإماراتي فوز الإمارات بر...,Culture
1,Khaleej,Culture,استضاف مركز الشارقة لفن الخط العربي والزخرفة م...,Culture

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(test_samples['subdirectory'],
                            test_samples['Predicted Class'],
                            digits =4 ))

              precision    recall  f1-score   support

     Culture     0.9859    0.9333    0.9589       150
     Finance     0.9177    0.9667    0.9416       150
     Medical     0.9866    0.9800    0.9833       150
    Politics     0.9610    0.9867    0.9737       150
    Religion     0.9515    0.9800    0.9655       100
      Sports     0.9934    1.0000    0.9967       150
        Tech     0.9790    0.9333    0.9556       150

    accuracy                         0.9680      1000
   macro avg     0.9679    0.9686    0.9679      1000
weighted avg     0.9687    0.9680    0.9680      1000