# Install Dependencies

In [ ]:
!pip install -q openai

In [ ]:
!pip install -q sacrebleu
!pip install -q rouge-score
!pip install -q bert-score
!pip install git+https://github.com/huggingface/evaluate@32546aafec25cdc2a5d7dd9f941fc5be56ba122f

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 8.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for rouge-score (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 122.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 100.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 20.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 111.8 MB/s eta 0:00:00
Collecting git+https://github.com/huggingface/evaluate@32546aafec25cdc2a5d7dd9f941fc5be56ba122f
  Cloning https://github.com/huggingface/evaluate (to revision 32546aafec25cdc2a5d7dd9f941fc5be56ba122f) to /tmp/pip-req-build-676romc2
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/evaluate /tmp/pip-req-build-676romc2
  Running command git rev-parse -q --verify 'sha^32546aafec25cdc2a5d7dd9f941fc5be56ba122f'
  Running command git fetch -q https://github.com/huggingface/evaluate 32546aafec25cdc2a5d7dd9f941fc5be56ba122f
  Resolved https://github.com/huggingface/evaluate to commit 32546aafec25cdc2a5d7dd9f941fc5be56ba122f
  Preparing metadata (setup.py) ... done
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate==0.4.5.dev0) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (0.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.5.dev0) (24.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate==0.4.5.dev0) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate==0.4.5.dev0) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate==0.4.5.dev0) (6.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate==0.4.5.dev0) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate==0.4.5.dev0) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate==0.4.5.dev0) (1.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate==0.4.5.dev0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate==0.4.5.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate==0.4.5.dev0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate==0.4.5.dev0) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate==0.4.5.dev0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate==0.4.5.dev0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate==0.4.5.dev0) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.5.dev0) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate==0.4.5.dev0) (1.17.0)
Building wheels for collected packages: evaluate
  Building wheel for evaluate (setup.py) ... done
  Created wheel for evaluate: filename=evaluate-0.4.5.dev0-py3-none-any.whl size=84157 sha256=84cc9623d05458a4373a8e8475017d138241055bf1e9cb7cd82f17864250fe30
  Stored in directory: /root/.cache/pip/wheels/89/96/43/3d812abd89a5bdb5c4e6156d219fdb043db5fb31137b368aee
Successfully built evaluate
Installing collected packages: evaluate
Successfully installed evaluate-0.4.5.dev0

# Load Modules

In [ ]:
import pandas as pd
import json
from openai import OpenAI
from sklearn.model_selection import train_test_split
import re

client = OpenAI(api_key='API_KEY')

# Define Functions

In [ ]:
def format_prompt(data):

    """

    Background: This function helps format data into a list of dicts into the required shape for fine tuning

    Params:
    data (list): list of dicts

    Returns:
    training_data_list (list): a list in the proper format for converting to jsonl

    """

    training_data_list = []

    for x in data:

        updated_data = {
            "messages": [
                {
                    "role": "system",
                    "content": x['system_message']
                },
                {
                    "role": "user",
                    "content": x['user_content']
                }
            ]
        }

        training_data_list.append(updated_data)

    print(training_data_list)

    return training_data_list

In [ ]:
def convert_to_jsonl_and_save(data_list, filename):

    """
    Background:
    This function converts the data_list provided into a jsonl file

    Params:
    data_list (list): a list of a dict ready to convert to jsonl
    filename (str): the name of the filename we want to convert

    """

    with open(filename, 'w') as file:
        for data_dict in data_list:
            json_str = json.dumps(data_dict)  # Convert dictionary to JSON string
            file.write(json_str + '\n')  # Write to file with a newline

    print(f"✅ Data successfully written to {filename}")

In [ ]:
def predict(test, model):
  response = client.chat.completions.create(
      model = model,
      messages= test,
      temperature = 0.2,
      max_tokens= 512
  )
  return response.choices[0].message.content

In [ ]:
def store_predictions(test_df, model, test_data):
  print("fine tuned model id is :", model)
  test_df['Prediction']= None

  for index, row in test_df.iterrows():
    test_message = test_data[index]['messages']
    prediction_result = predict(test_message, model)
    test_df.at[index, 'Prediction'] = prediction_result

  test_df.to_csv("predictions.csv")

# Load Model

In [ ]:
model = 'gpt-4o-2024-08-06'

# Load Data

In [ ]:
data = pd.read_excel('summarization_data.xlsx')

In [ ]:
import re

def normalize_arabic(text):
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"[ًٌٍَُِّْ]", "", text)  # Remove short vowels (diacritics)
    text = re.sub(r"[^\w\s]", "", text)    # Remove punctuation (optional)
    return text.strip()

# Zero Shot

## Prepare Prompt

In [ ]:
data['system_message'] = 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'
data['user_content'] = 'Passage: \n' + data['text'] + '\n Summary:'

data2 = data
data = data[['system_message','user_content']]

In [ ]:
data.to_excel('SA-ZeroShot-gpt.xlsx')

In [ ]:
# Convert to JSON String
data = data.to_json(orient='records')

# parse JSON string and convert it into a list of python dictionaries
datadict = json.loads(data)

## Format Prompt

In [ ]:
# format dict into shape for fine tuning
zero_shot_data = format_prompt(datadict)

[{'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nواستحوذت القصة على نقاشات رواد مواقع التواصل الاجتماعي، حيث تصدرت وسوم مثل "#ابن_القاضي وشرطي المرور" قائمة المواضيع المتداولة على تويتر لساعات طويلة. واكب المغردون تطورات القضية بدءا من مرحلة استجواب الطفل والإفراج عنه وحتى إعادة توقيف وإيداعه لدار رعاية في وقت لاحق. فقد أفادت تقارير صحفية بإعادة توقيف الطفل وأربعة من رفاقه صباح الاثنين 2 نوفمبر/ تشرين الثاني. ووصفت تلك التقارير حالة "الهلع والبكاء" التي انتابت الأطفال. للقصة جوانب ودلالات عديدة، فـ "بـطلها طفل يقود سيارة فارهة ويعرض حياته وحياة المارة للخطر، ويهين شرطيا طالبه باستظهار رخصته". مواضيع قد تهمك نهاية كل تلك المعلومات كانت كافية لجعل الموضوع يتصدر اهتمام المصريين، الذين حذروا أيضا مما وصفوها بـ"ظاهرة الإفلات من العقاب واستغلال النفوذ". فما التفاصيل؟ النيابة توضح في أواخر الأسبوع الماضي، انتشر مقطع للواقعة بكثافة عبر مواقع التواصل الاجتماعي، وسط غضب المصريين الذين طالبوا بمعاقبة الطفل ووالده. وتعود الواقعة إلى 26 أكتوبر / تشرين الثاني، عندما تقدم المارة بشكوى لشرطي مرور وأبلغوه بوجود شخص يقود سيارة برعونة، فاستوقف السيارة، ليكتشف أن السائق طفل يرافقه آخرون من نفس العمر. ويظهر الشرطي في الفيديو المتداول وهو يسأل الطفل عن رخصة القيادة، فصُدم بكيل من الشتائم تنهال عليه وبسخرية الأطفال منه وتوعدهم بإيذائه. ويتعذر على بي بي سي نشر الفيديو احتراما لخصوصية الأطفال. وبمجرد انتشار الفيديو عبر مواقع التواصل، أعلنت النيابة العامة في بيان نشرته على فيسبوك، فتح تحقيق في الواقعة واتخاذ الإجراءات اللازمة. لكن بيانا آخر يفيد بإخلاء سبيل الطفل بناء على طلب الأخصائي النفسي، قوبل بموجة استنكار، إذ طالب مغردون بـ"معاقبة الطفل وأبيه المستشار وتحميل الأخير المسؤولية كاملة حتى لا يتكرر الموقف ثانية". وكانت النيابة قد أشارت في بيانها الثاني إلى أن "السيارة التي كان يستقلها الطفل مملوكة لصديق والده، وقام باختلاس مفاتيح السيارة دون علم صاحبها". وحملت النيابة المسؤولية لصديق العائلة واكتفت بتغريمه 10 آلاف جنيه مصري أي ما يعادل 600 دولار أمريكي. ويبدو أن موجة الغضب قد دفعت السلطات إلى القبض على الطفل مرة أخرى. وأعلنت النيابة العامة في بيان نشرته مساء الاثنين، إيداع لـ "دار ملاحظة" لمدة أسبوع وطلب مذكرة من والده المستشار. كما قررت حبس أصدقائه أربعة أيام وعرضهم على الطب الشرعي لإجراء تحليل للتأكد من تعاطيهم للمخدرات. أزمة "مؤسسات" أم"أفراد"؟ وانتقد مغردون في بدء الأمر "تساهل السلطات في التعامل مع نجل مستشار انتهك القانون"، واحتفوا لاحقا بخبر إيقافه . في حين دعا المتحدث باسم نادي قضاة مصر إلى ضرورة الفصل بين الواقعة وصفة أبيه القضائية، مضيفا أنها "لن تعطل أو تتدخل في سير التحقيقات على عكس ما يروجه بعض المغرضين". كما حذر آخرون من تضخيم الموضوع وعملية "الشيطنة التي يقودها البعض ضد الطفل وأسرته" وفق تعبيرهم. وكان ممثلون وإعلاميون ومسؤولون قد عبروا عن غضبهم الشديد من الواقعة، التي اتفقوا على وصفها بـ "المشينة". ومن بين هؤلاء الممثل عبد الرحمن حسن والصحفي والبرلماني محمود بدر. واستدعى نشطاء قضايا لأطفال ومراهقين تم إيقافهم أو سجنهم لـ "أسباب بسيطة وأخرى تتعلق بآراء سياسية " قائلين إن "تلك القضايا كشفت ازدواجية الشرطة في التعامل مع أبناء الشعب الواحد" . كذلك طالب البعض بمحاسبة رجال شرطة المرور لـ"تهاونهم" في إيقاف الطفل، إذ غرد محمود سعيد قائلا" مقاطع عديدة تؤكد أن الطفل كرر فعلته أكثر من مرة، أمام أعين رجال الشرطة الذين اكتفوا بالتحديق به، لماذا يضع حدا للمشكلة؟ ثم كيف لأمه أن تتركه بدون رقابة؟" بينماأشاد آخرون بدور الشرطي الذي أصر على إيقاف الطفل وطلب منه رخصة السيارة، مطالبين بتكرميه. وما زاد من غضب البعض هو "نشر الطفل مقطعا عبر حسابه على انستغرام وهو يتباهى بسلطة والده، بعد انتهاء الاستجواب"، وفق ما قاله بعض المغردين. كما نشر البعض الآخر فيديوهات قالوا إنها تؤكد أن الطفل سبق أن قاد السيارة في مناسبات عديدة وأنه كان معتادا على إهانة رجال شرطة المرور" . وبحسب صحيفة "الدستور" المصرية فإن الشرطة ألقت القبض على الطفل وأربعة من أصدقائه بسبب إساءة استخدام وسائل التواصل الاجتماعي. وجددت تلك التفاصيل النقاش حول السبل التي يجب اتباعها لتقويم هذا السلوك. وفي الوقت الذي طالب فيه عمرو أديب بضم الطفل إلى "معسكر خاص يعلمه الانضباط واحترام الآخرين"، طالب آخرون بتحويله للأحداث، في حين عارض آخرون تلك الفكرة التي رأوا أن من شأنها هدم شخصية الطفل بدلا من إصلاحه. واستندت النيابة العامة في قرارها الأول، إلى رأي اختصاصي اجتماعي تابع للمجلس القومي للطفولة والأمومة. وذكر الاختصاصي في تقرير تداولته صحف محلية أن الطفل "مدلَل بشدة من والده". ونصح بـ"تسليمه لأهله والتعهد عليهم بتقويم سلوكه، وعقد جلسات دورية معه".\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nوسيوفر البرنامج خمسة كيلوغرامات من الحبوب الرخيصة كل شهر لنحو 800 مليون فقير. ووجهت انتقادات لوزراء لتمرير القرار كمرسوم إثر إخفاقهم في الحصول على تأييد البرلمان. ويقول منتقدو البرنامج إن الخطة تحرك سياسي للحصول على تأييد سياسي وإنها ستجهد اقتصاد الهند. ويقول مؤيدوها إنها ستحد من الفقر. وقال كيه في توماس وزير الموارد الغذائية للصحفيين اثر اجتماع لمجلس الوزراء "اقر مجلس الوزراء مرسوم الأمن الغذائي بالإجماع"، مما يعني أنه سيصبح قانونا على الفور ولكن يجب أن يصدق عليه البرلمان في نهاية الأمر. مواضيع قد تهمك نهاية سوء التغذية ويعد برنامج الأمن الغذائي القومي واحدا من اكبر برامج الرعاية الاجتماعية في العالم. وكان حزب المؤتمر الحاكم قد قدم تعهدا انتخابيا بتمرير برنامج الدعم الغذائي، ويقول المراسلون إن تنفيذه سيساعد الحزب في الانتخابات العامة المزمع إجراؤها العام المقبل. ووضع البرنامج لمكافحة الجوع، فعلى الرغم من النمو الاقتصادي الكبير الذي شهدته الهند في الاعوام الأخيرة، إلا إنها ما زالت تواجه صعوبات في توفير الغذاء لسكانها. ويوجد في الهند أطفال مصابون بسوء التغذية اكثر من أي بلد آخر في العالم. وبموجب المرسوم سيتم تقديم الكيلوغرام من الأرز بسعر ثلاثة روبيات (ستة سنتان امريكية) والدقيق (الطحين) بسعر روبيتين. ويقول سانجوي ماجومدير إن المرسوم سيسري على 75 بالمئة من الهنود المقيمين في المناطق الريفية و50 بالمئة من المناطق الحضرية. ولكن الكثير من خبراء الاقتصاد يتشككون في قدرة الهند على تمويل برنامج بهذ الضخامة، حيث سيؤدي إلى مضاعفة الدعم الغذائي ليصل إلى أكثر من 1.3 تريليون روبية (239 مليار دولار). وتؤكد الحكومة أن توفير الأموال اللازمة للبرنامج لا يمثل مشكلة.\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nكان ديفيد سورنسن يعمل كاتب خطابات في البيت الأبيض وينفي ديفيد سورنسن ادعاءات زوجته السابقة بأنه كان عنيفا معها بدنيا ونفسيا. وتأتي استقالة سورنسن بعد أيام فقط من استقالة روب بورتر من منصب سكرتير شؤون الموظفين في البيت الأبيض وسط مزاعم بارتكابه انتهاكات بحق زوجتين سابقتين له. ونفى بورتر أيضا صحة هذه المزاعم. وأثيرت تساؤلات حول مدى سرعة استجابة البيت الأبيض، للاتهامات الموجهة بورتر. ما هي المزاعم الأخيرة؟ صرحت جيسيكا كوربت، زوجة سورنسن السابقة، لصحيفة واشنطن بوست بأنه كان يمارس ضدها عنفا بدنيا، حينما كانت متزوجة منه. وأضافت أنه في مناسبات منفصلة، قام زوجها السابق بتمرير سيارة فوق قدمها، وأنه صدمها بحائط، وأطفأ السجائر في يدها. وفي رد فعل، أصدر سورنسن بيانا، قال فيه إنه "لم يرتكب أي عنف من أي نوع، تجاه أي امرأة في حياته على الإطلاق"، بل وبدلا من ذلك، قال إنه هو من تعرض لعنف بدني. وقال سورنسن إنه يدرس اتخاذ إجراء قانوني، حيال تلك المزاعم، لكنه أوضح أنه استقال من منصبه لأنه "لم يرغب في أن ينخرط البيت الأبيض في تلك الصغائر". وقال مسؤولون في البيت الأبيض إنهم علموا بالاتهامات، الموجهة لسورنسن من جانب زوجته، في وقت متأخر من الخميس. وأوضح نائب المتحدث الصحفي باسم البيت الأبيض: "لقد واجهنا سورنسن على الفور، ونفى تلك المزاعم، واستقال من منصبه اليوم". ما قصة بورتر؟ ظهرت المزاعم بارتكاب بورتر عنفا منزليا، ضد زوجتيه السابقتين، الثلاثاء الماضي. واستقال بورتر من منصبه الأربعاء، وقال في بيان استقالته إن "هذه المزاعم المشينة هي بكل بساطة كاذبة". وأشاد الرئيس الأمريكي، دونالد ترامب، الجمعة بمساعده بورتر. وقال ترامب متحدثا من المكتب البيضاوي: "لقد اكتشفنا ذلك مؤخرا، وفوجئت بذلك، لكننا بالطبع نتمنى له الخير. إنه وقت عصيب بالنسبة له". ولم يشر ترامب إلى من وجهوا تلك المزاعم ضد بورتر. وأثارت تصريحات ترامب تلك انتقادات من جانب الديمقراطيين، حيث اعتبر جو بايدن، نائب الرئيس الأمريكي السابق، أن ترامب قلل من أهمية المزاعم ضد بورتر. وقال بايدن: "هذا الأمر يشبه كما لو أنك تقول: هذا القاتل الذي يقف هناك، إنه رسام رائع".\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nظهرت أعراض اصابات متوسطة في الدماغ وفقدان سمع دائم لدى بعض العاملين في السفارة الأمريكية في هافانا وكان يعتقد ،في البداية، أن أمثال هذه الحوادث قد انتهت قبل بضعة أشهر، لكن وزارة الخارجية الأمريكية قالت أيضا إن عدد العاملين في السفارة الذين أفادوا بتعرضهم لمشاكل صحية قد ارتفع مؤخرا إلى 19 شخصا. يأتي ذلك في وقت قالت فيه الرابطة التي تمثل الكوادر الدبلوماسية إن بعض الضحايا يعانون من إصابات متوسطة في الدماغ وحالات فقدان سمع دائم. ونفت كوبا ضلوعها في أي هجمات، قائلة إنها تحقق في هذه التقارير. وقد لاحظ الكادر الدبلوماسي الأمريكي وأحد الكنديين على الأقل هذه الأعراض في أواخر العام الماضي. على الرغم من أن هذا الامر قد أثير للمرة الأولى في اغسطس /آب عندما أبعدت الولايات المتحدة اثنين من الدبلوماسيين الكوبيين من واشنطن، وقال المسؤولون إن الإبعاد كان احتجاجا على فشل كوبا في حماية الدبلوماسيين لديها. وأشارت وسائل إعلام أمريكية إلى أنه ربما استخدمت أجهزة صوتية لتوليد موجات صوتية غير مسموعة قد تسبب الصمم. وأكدت الحكومة الأمريكية الجمعة أن الحادثة وقعت مؤخرا في شهر أغسطس/آب، وقد تزايد عدد العاملين الذين تعرضوا لمشكلات صحية. __________________________________________________________________________________________________________________ الهجمات "الصوتية" في كوبا _____________________________________________________________________________________________________________________ وقالت المتحدثة باسم الخارجية الأمريكية هيذر ناويت "لا نستطيع استبعاد وجود حالات جديدة، إذ يواصل كادر طبي محترف فحص وتقييم أوضاع عدد من العاملين في السفارة". وقالت رابطة الخدمات الخارجية الأمريكية، التي تمثل الدبلوماسيين الأمريكيين والكوادر الدولية المساعدة لهم، في بيان إنها تحدثت إلى 10 أشخاص تلقوا معالجة طبية. وأضاف البيان "وتشمل التشخيصات حالات إصابات دماغية متوسطة وفقدان سمع دائم، فضلا عن أعراض إضافية كفقدان التوازن، وصداع حاد، واضطراب إدراكي وتورم في الدماغ". وحضت الحكومة على أن تفعل كل ما في وسعها لمساعدة المتضررين و"لضمان عدم تكرر مثل هذه الحوادث". طُلب من اثنين من الدبلوماسيين الكوبيين مغادرة الولايات المتحدة ويعد هذا البيان المرة الأولى التي يشار فيها إلى وجود حالات فقدان سمع دائم. وقد فهم أن عبارة " إصابات دماغية متوسطة" تشمل حالات ارتجاج الدماغ والصداع. ولم تُلق الخارجية الأمريكية اللوم في التسبب في أمثال هذه الحوادث على أحد، حتى الآن. وقد أعيد افتتاح البعثة الدبلوماسية الأمريكية في هافانا، في تمثيل كامل على مستوى سفارة في عام 2015، في أعقاب نحو نصف قرن من العلاقات العدائية بين البلدين.\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nوانطلق نقاش محتدم حول الصورة بعد أن نشرها الأمير السعودي بن خالد آل سعود ليتصدر في أعقابها وسم "الحرس الملكي" قائمة المواضيع الأكثر تداولا على موقع تويتر وغوغل في السعودية. وتظهر الصورة المثيرة للجدل، سيدة ترتدي الزي الرسمي للحرس الملكي وتقف إلى جانب زميلها أمام بوابة يعتقد أنها داخل القصر الملكي في الرياض. ورحب شق من المغردين بفكرة انتساب النساء للحرس الملكي، أسوة بالرجال واعتبروها خطة جيدة لتمكين المرأة وتحقيق المساواة المطلوبة بين الجنسين في المجتمع. وتساءلت بعض الفتيات عن شروط الانضمام للحرس الملكي مبديات حماسهن للوظيفة الجديدة. مواضيع قد تهمك نهاية وترى كثيرات أن تلك الصورة ستسهم في تغيير الصورة النمطية لعمل المرأة التي تحصر عادة ضمن وظائف تربوية وإدارية محددة. في المقابل، عارض قطاع آخر من المغردين فكرة توظيف النساء بالمؤسسة الأمنية عموما. كما انتقد بعضهم تعيين السيدات في الحراسة الشخصية قائلين إن المساواة العادلة لا تعني بالضرورة توظيف النساء في الحرس الملكي. ويعتقد كثيرون أن المجتمع السعودي ما زال "غير مؤهل لتقبل فكرة انتساب النساء للمؤسسة الأمنية واختلاطهن بزملائهن من الرجال، لأن تركيبته المحافظة ترفض تلك الفكرة وترى فيها تهديدا لعاداته وتقاليده". انفتاح حقيقي أم صوري؟ في المقابل، يرى مغردون أن تعيين السيدة في الحرس لم يأتِ مصادفة، إنما نتيجة ارتفاع منسوب الوعي لدى المجتمع وتقبل العائلات لفكرة التحاق بناتهن بالمؤسسة الأمنية، على حد تعبيرهم. وحثت مغردات الحكومة على تكثيف الجهود لتوظيف النساء في مناصب ظلت حكرا على الرجال. وتقول مغردات إن المجتمع السعودي خسر الكثير في السابق بسبب إقصاء المرأة عن المشاركة الكاملة في هذا الجانب، وأشرن إلى أهمية تواجد عنصر نسائي عند التوجه للمنازل من أجل تفتيشها أو القبض على مطلوبين للعدالة. ومنذ سنوات، سعى ولي العهد الشاب محمد بن سلمان إلى تحسين صورة بلاده دوليا بإطلاق رؤية 2030 التي نجحت برأي كثيرين في تنفيذ حزمة من الإصلاحات نالت المرأة القسط الأكبر منها. ومنحت تلك الإجراءات السعوديات حرية أوسع في التنقل والسفر وإجراء المعاملات الرسمية. كما سمحت لهن بقيادة السيارة وحضور الفعاليات الرياضية والفنية وغيرها. وينظر كثيرون للإجراءات المتتالية وصورة المرأة المنتسبة للحرس الملكي على أنها "حصيلة للإصلاحات التي نفذها ولي العهد السعودي" ويعتبرونها دليلا على "تقدم المرأة السعودية على نظيراتها في مجتمعات عربية أخرى". في حين يشكك نشطاء وحقوقيون في تلك الإجراءات ويصفونها بالشكلية. ويقول هؤلاء إن اعتقال الناشطات ومحاكمتهن بتهم تتعلق بنشاطهن الحقوقي يفند مصداقية تلك الإصلاحات والتغريدات التي تتغنى بالإنجازات التي حققتها المرأة السعودية. من جهة أخرى، يثمن معلقون تلك المكتسبات والإصلاحات، إلا أنهم يرون أنها لن تحقق الأهداف المرجوة منها ما دامت المرأة تتعرض للعنف المنزلي وتعامل على أنها كائن ناقص وتمنع من نقل جنسيتها لأبنائها". لذا ينادي هؤلاء بتكثيف حملات التوعية بحقوق المرأة وبإعطائها قدرا أكبر من الحريات السياسية حتى لا تبقى تلك الإصلاحات "قاصرة على فئة معينة من النساء". في حين يدافع آخرون عن توجهات الحكومة ويرون أن المرأة السعودية نالت كامل حقوقها وأنها توجتها بقرار إلحاق النساء بالمؤسسة الأمنية والعسكرية. وكانت وزارة الدفاع السعودية قد فتحت في 4 أكتوبر/ تشرين الأول الماضي، باب القبول والتسجيل للنساء الراغبات في الحصول على وظائف عسكرية برتبة "جندي أول أو رقيب أو عريف". واللافت أن شروط التقديم للتجنيد، تشمل أن تكون المرأة في الفئة العمرية بين (21-40 عاما)، وأن يكون الحد الأدنى لطولها 155 سم، وأن يكون وزنها متناسقا مع قامتها. كما ينص القانون على أن تكون سعودية الأصل والمنشأ إضافة إلى وجوب ألا تكون متزوجة من غير سعودي. وسبق أن عملت المرأة السعودية في صفوف الحرس الملكي لتأمين القسم الخاص بإقامة العائلة. كما أنها تشتغل في السلك الأمني منذ سنوات، خاصة في إدارات السجون والجوازات، بحسب ما ذكره صحفيون سعوديون.\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nرومني دعى في خطابه إلى أن يكون لبلاده دور اكثر فعالية في سوريا وان تتغير شروط المعونة لمصر وقال في خطاب ألقاه الأثنين في معهد فرجينيا العسكري إن الأخطار التي تحدق بعملية السلام في الشرق الأوسط زادت خلال الفترة الرئاسية لمنافسه الديموقراطي. وأعرب رومني عن أمله في أن يتمكن من الغاء سلسلة من السياسات الخارجية التي اتخذها أوباما التي وصفها "بالمتعثرة" على حد تعبيره. وقال "إن هناك رغبة أمريكية كبيرة في الإمساك بزمام الامور في الشرق الاوسط". كما دعى رومني إلى أن يكون لبلاده دور اكثر فعالية في سوريا وان تتغير شروط المعونة لمصر وأن تفرض عقوبات اكثر صرامة على إيران. ومع تسارع وتيرة حملات المرشحين الامريكين والاداء الضعيف لأوباما في المناظرة الاولى ضمن ثلاثة أخرين الاسبوع الماضي، يتطلع الناخب الامريكي للمناظرة القادمة بين نائبي المرشحين. ومن المقرر ان تعقد مناظرة بين جوبايدن وبول راين الخميس المقبل. وتسعى حملة رومني إلى تقليل فرص اوباما بين الناخبين المبكرين ويبدو أن ثمة مؤشرات على نجاح هذه الجهود في ولايتي نورث كارولينا وفلوريدا التي سيدفع الخاسر فيهما ثمنا باهظا في هذه الانتخابات. بينما يتقدم أوباما في ولاية ايوا التي مثل ساحة قتال أخرى للمرشحين للوصول إلى أصوات ناخبيها. وفي انتخابات 2008، سيطر أوباما على أصوات الأربع ولايات الرئيسية في التصويت المبكر متغلبا على خصمه في ذلك الوقت جون ماكين حتى قبل حلول يوم الانتخابات. اقرأ أيضا موضوعات ذات صلة\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nتسعى شركة لينوفو إلى أن تصبح شركة عملاقة عالمية واشترت غوغل أسهما في الشركة الصينية بقيمة 618.3 مليون دولار أي بـ 1.21 دولارا بالنسبة إلى السهم الواحد وذلك يوم 30 يناير/كانون الثاني، حسب سوق للأوراق المالية. وصرفت لينوفو الشهر الماضي 5 مليارات دولار من أجل شراء شركة موتورولا والجزء المتعلق بنشاط خوادم شركة أبي بي إم ذات الجودة المنخفضة. وانخفضت أسهم شركة لينوفو بنحو 1 في المئة في تعاملات بورصة هونغ كونغ الجمعة. وانتقد مستثمرون شركة لينوفو التي تتخذ من العاصمة الصينية بكين مقرا لها إسرافها في إبرام صفقات الاستحواذ الأخيرة. مواضيع قد تهمك نهاية وفقدت لينوفو 24 في المئة من قيمتها السوقية منذ الإعلان عن شرائها شركة موتورولا بقيمة 2.9 مليار دولار يوم 29 يناير/كانون الثاني الماضي. وخفضت 5 شركات سمسرة كبرى على الأقل توقعاتها بشأن لينوفو التي تحدثت علانية عن رغبتها في أن تكون عملاقا اقتصاديا عالميا. لكن المحللين غير متفائلين بشأن عمليات الاستحواذ الأخيرة، قائلين إن لينوفو ربما اشترت موتورولا بأكثر من قيمتها السوقية. ولذلك، فإن لينوفو ستواجه أوقاتا صعبة في سعيها لتحويل موتورولا التي لم تحقق أرباحا تذكر في الآونة الأخيرة إلى شركة مربحة. وشهدت شركة لينوفو التي أنشئت في عام 1984 توسعا كبيرا في نشاطاتها بفضل عمليات الاستحواذ التي قامت بها. لكن في ظل تجنب المستهلكين اقتناء أجهزة كمبيوتر شخصية مقابل شراء أجهزة أصغر وأكثر قابلية للحمل، فإن الشركة تتطلع إلى الانتشار بموجب ما يسمى خطة "الأجهزة الشخصية وزيادة". ونتجية لذلك، كشفت شركة لينوفو عن خطة تصنيع أجهزة كمبيوتر لوحية وهواتف محمولة رخيصة الثمن وذات جودة عادية والتي بيعت سواء في الصين أو في الأسواق الناشئة. واستعانت شركة لينوفو بممثلين مشهورين من هوليوود من أجل الترويج لمنتجاتها. وتأمل الشركة الآن في تصنيع منتجات أكثر تطورا من خلال شراء موتورولا واختراق الأسواق الأمريكية والأوروبية.\n Summary:'}]}, {'messages': [{'role': 'system', 'content': 'You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.'}, {'role': 'user', 'content': 'Passage: \nوكانت أسما ابنة الفنان المصري شريف منير قد طلبت من متابعيها عبر فيسبوك أن يرشحوا لها أسماء شيوخ يتمتعون بالمصداقية. وردت الإعلامية على شخص نصحها بالاستماع للشيخ الشعراوي:"طوال عمري أسمعه عن الشعراوي من جدي، لم أكن أفهم كل شيء آنذاك، لكن لما كبرت شاهدت فيديوهات، لم أصدق نفسي من شدة التطرف، كلامه لا يستوعبه عقلي". "خط أحمر" وفي غضون دقائق سيطرت التدوينة التي لم تتجاوز بضعة أسطر، على حديث رواد مواقع التواصل الاجتماعي وأصبحت مثار جدل تحت قبة البرلمان المصري. كما تصدر اسم الإعلامية قوائم الكلمات الأكثر بحثا على غوغل في مصر ليومين متتاليين. مواضيع قد تهمك نهاية فقد جرت التدوينة على صاحبتها سيلا من الانتقادات اللاذعة، ما اضطرها إلى حذفها والاعتذار. ثم أغلقت جميع حساباتها عبر وسائل التواصل الاجتماعي، وظهرت في إحدى البرامج وهي تبكي وتطلب من الناس أن تسامحها. ولكن الاعتذار لم يشفع لأسما، إذ انبرى مغردون في إطلاق وسوم تطالب بمعاقبتها وتذود عن الشيخ الراحل. ولعل أبرز تلك الوسوم وأكثرها انتشارا وسمي #الشعراوي_رمز_مصر و #الشعراوي_خط_احمر . واتهم المتفاعلون مع هذه الوسوم الإعلامية المصرية بإهانة رمز من رموز الإسلام، حتى أن البعض كفر الإعلامية. ووصل الحماس ببعض المدافعين عن الشيخ الأزهري حد التهديد بالقتل. كما أعلن نواب في البرلمان المصري اعتزامهم تقديم بلاغ عاجل ضد أسما. فقد اتهمتها النائبة آمنة نصير، باللهث وراء الشهرة من خلال التطاول على الشعراوي. في حين وصف النائب إسماعيل نصر الدين، تصريحات أسما بـ"غير المسؤولة والجاهلة". "تقديس لرجال الدين"

In [ ]:
# Save as jsonl
convert_to_jsonl_and_save(zero_shot_data, 'SA-ZeroShot.jsonl')

✅ Data successfully written to SA-ZeroShot.jsonl

## Predict

In [ ]:
# response = client.chat.completions.create(
#       model = model,
#       messages= zero_shot_data[1]['messages'],
#       temperature = 0.2,
#       max_tokens= 512
#   )

# response.choices[0].message.content

'Neutral'

In [ ]:
true = pd.read_excel('summarization_data.xlsx')
y_true = true['summary'].values

In [ ]:
zs = pd.DataFrame()

zs['text'] = data2['text']
zs['summary'] = y_true
zs = zs.reset_index(drop=True)
zs.head()

,text,summary
0,واستحوذت القصة على نقاشات رواد مواقع التواصل ا...,أثار مقطع فيديو يظهر طفلا يقود سيارة ويعتدي لف...
1,وسيوفر البرنامج خمسة كيلوغرامات من الحبوب الرخ...,دشنت الحكومة الهندية برنامجا ضخما لتوفير الغذا...
2,كان ديفيد سورنسن يعمل كاتب خطابات في البيت الأ...,أصبح ديفيد سورنسن، كاتب الخطابات في البيت الأب...
3,ظهرت أعراض اصابات متوسطة في الدماغ وفقدان سمع ...,تعرض العاملون في السفارة الأمريكية في كوبا إلى...
4,وانطلق نقاش محتدم حول الصورة بعد أن نشرها الأم...,استأثرت صورة امرأة في صفوف الحرس الملكي السعود...

In [ ]:
store_predictions(zs, model, zero_shot_data)

fine tuned model id is : gpt-4o-2024-08-06

In [ ]:
pred_zero = pd.read_csv('TextSummarization-GPT4o-ZeroShot-predictions.csv')

In [ ]:
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import sacrebleu
import evaluate
from transformers import AutoTokenizer

# Initialize storage
bleu_scores = []
bleu_scores2 = []
rougeL_p = []
rougeL_r = []
rougeL_f = []
bertscore_p = []
bertscore_r = []
bertscore_f = []

# Initialize scorer
model_name = 'aubmindlab/bert-base-arabertv2'
tokenizer = AutoTokenizer.from_pretrained(model_name)
rouge = rouge_scorer.RougeScorer(['rougeL'], tokenizer=tokenizer)

# Iterate through rows
for _, row in pred_zero.iterrows():
    raw_references = [row['summary']]  # One reference as list of strings
    raw_predictions = [row['Prediction']]  # One prediction

    # Normalize Arabic
    hyp = [normalize_arabic(text) for text in raw_predictions]
    ref = [[normalize_arabic(ref) for ref in raw_references]]  # Nested list for multiple refs per prediction

    # BLEU
    bleu = sacrebleu.corpus_bleu(hyp, ref)
    bleu_scores.append(bleu.score)

    bleu2 = evaluate.load("bleu")
    results = bleu2.compute(predictions= hyp, references= ref)
    bleu_scores2.append(results['bleu'])

    # ROUGE-L
    r_scores = rouge.score(row['summary'], row['Prediction'])
    rougeL_p.append(r_scores['rougeL'].precision)
    rougeL_r.append(r_scores['rougeL'].recall)
    rougeL_f.append(r_scores['rougeL'].fmeasure)

# BERTScore
P, R, F = bert_score(pred_zero['Prediction'].tolist(), pred_zero['summary'].tolist(), lang="ar", model_type="bert-base-multilingual-cased", verbose=False)
bertscore_p = P.tolist()
bertscore_r = R.tolist()
bertscore_f = F.tolist()

# Create summary DataFrame
metrics_df = pd.DataFrame({
    "BLEU1": bleu_scores,
    "BLEU2": bleu_scores2,
    "ROUGE_L_P": rougeL_p,
    "ROUGE_L_R": rougeL_r,
    "ROUGE_L_F": rougeL_f,
    "BERT_P": bertscore_p,
    "BERT_R": bertscore_r,
    "BERT_F": bertscore_f,
})

# Calculate min, max, mean
summary_stats = metrics_df.agg(['min', 'max', 'mean'])

print(summary_stats)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/611 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/384 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

          BLEU1     BLEU2  ROUGE_L_P  ROUGE_L_R  ROUGE_L_F    BERT_P  \
min    0.000000  0.000000   0.007092   0.027027   0.011236  0.574788
max   17.548433  0.175484   0.438356   0.633333   0.470588  0.777178
mean   2.961511  0.009043   0.131799   0.265503   0.171988  0.688352

        BERT_R    BERT_F
min   0.591935  0.591594
max   0.882943  0.799640
mean  0.730025  0.708294

# Few Shot

## Prepare Prompt

In [ ]:
data['system_message'] = '''You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.

Example 1:
Passage:
وكان الرئيس الأوكراني المؤقت، الكسندر تورتشينوف، قد أمر بسحب جميع القوات الأوكرانية من القرم. وسيطرت قوات روسية صباح الاثنين على قاعدة بحرية أوكرانية في فيودوسيا، في ثالث هجوم من نوعه خلال 48 ساعة، وذلك بحسب تصريحات مسؤولين أوكرانيين لبي بي سي . وقال المتحدث باسم وزارة الدفاع الأوكرانية فلاديسلاف سيليزنيوف إن القوات الروسية هاجمت القاعدة وألقت القبض على الجنود الأوكرانيين في قاعدة فيودوسيا وقيدت أيادي ضباطهم. ومن المتوقع أن تسيطر الأزمة الأوكرانية على قمة مجموعة الدول الصناعية السبع في لاهاي. مواضيع قد تهمك نهاية وأكد الرئيس الأمريكي باراك أوباما خلال لقاء مع نظيره الصيني شى جين بينغ على أن \"واشنطن وبكين يمكنهما، بالعمل سويا، تعزيز القانون الدولي واحترام سيادة الدول\". وتسيطر قوات روسية حاليا على معظم القواعد العسكرية الأوكرانية في القرم التي أعلنت موسكو ضمها للاتحاد الروسي بعد استفتاء أجرته السلطات المحلية هناك. قلق بالغ وقال مارك لوين، مراسل بي بي سي في القرم، إن القوات الروسية تسيطر بشكل كامل على القاعدة، ونقلت الجنود الأوكرانيين بعيدا إلى مكان مجهول. وتعد قاعدة فيودوسيا واحدة من آخر القواعد العسكرية التي بقيت تحت سيطرة كييف، لكن قوات روسية ظلت تحاصرها لبعض الوقت، حسبما أفاد مراسلنا. واقتحمت القوات الروسية قاعدتين أخريين وسيطرت عليهما يوم الجمعة. وكان مسؤولون عسكريون روس أعلنوا في وقت سابق أن العلم الروسي أصبح يرفرف على 189 وحدة ومنشأة عسكرية أوكرانية في القرم. وقال ديفيد ستيرن مراسل بي بي سي في كييف إن الأوكرانيين يتابعون هذه التطورات بقلق بالغ. وأشار إلى أن السؤال الذي يدور الآن هو ماذا سيكون رد فعل أوكرانيا والغرب وما هي الخطوة الروسية المقبلة. وحذر قائد الناتو في أوروبا يوم الأحد من أن القوات الروسية المنتشرة على الحدود الشرقية لأوكرانيا قادرة على شن عملية تمتد حتى مولدوفا. قمة الدول الصناعية الكبرى أوباما: العقوبات الغربية على موسكو ستؤثر على الاقتصاد الروسي. ويلقي ضم روسيا لمنطقة القرم بظلاله على قمة مجموعة السبع، التي كان مزمعا عقدها منذ فترة طويلة، بشأن تهديدات الأمن النووي. ومن المتوقع أن يبحث زعماء المجموعة موقفا موحدا حيال الأزمة. وأكد الرئيس الأمريكي على أن أوروبا والولايات المتحدة متفقون على دعم الحكومة الأوكرانية وشعبها، مشيرا إلى أن العقوبات التي فرضت على موسكو ستؤثر على الاقتصاد الروسي. ومن المقرر أن يلتقي وزير الخارجية الأمريكي، جون كيري، مع نظيره الروسي، سيرغي لافروف، على هامش قمة مجموعة السبع. انقطاع الكهرباء من جهة أخرى، شكا سكان محليون في بعض مناطق القرم من انقطاع الكهرباء في وقت متأخر من الأحد. ولف الظلام العديد من المدن من بينها بعض أحياء العاصمة سيمفربول. وقالت شركة توريد الكهرباء في القرم \"كريمنيرغو\" في بيان بث على موقعها الإلكتروني إن عطلا فنيا أصاب أحد الخطوط التي تديرها شركة الكهرباء الوطنية الأوكرانية \"اوكرينيرغو\". ولم يتسن الحصول على تعليق من اوكرينيرغو، ولم يصدر أيضا تأكيد مستقل حول سبب انقطاع الكهرباء. ضم القرم وضمت روسيا القرم إليها عقب استفتاء أجري في المنطقة في 16 مارس/آذار. وجاءت الخطوة الروسية بعد أن أطاحت احتجاجات بالرئيس الأوكراني السابق الموالي لروسيا فيكتور يانوكوفيتش. وأكدت روسيا أنها تحركت لحماية مواطني القرم المتحدرين من أصول روسية ضد من وصفتهم \"بالفاشيين\" الذين انتقلوا إليها من البلد الأم أوكرانيا. وردت الولايات المتحدة والاتحاد الأوروبي بفرض سلسلة من العقوبات ضد أفراد من بينهم مسؤولون بارزون اتهمتهم واشنطن وبروكسل بلعب دور في ضم القرم. موالون لروسيا يتظاهرون في مدينة مدينة دونيتسك، شرقي أوكرانيا. تسيطر قوات روسية حاليا على معظم القواعد العسكرية الأوكرانية في القرم.

Summary:
بدأت القوات الأوكرانية الانسحاب من شبه جزيرة القرم.

Example 2:
Passage:
وذكرت وكالة الأنباء المحلية (جي.إن.إس) أن جماعة \"جيش محمد\" المتشددة أعلنت مسؤوليتها عن الهجوم. لكن ما هي منطقة كشمير المتنازع عليها بين الهند وباكستان؟ خلال العقود الست الماضية ظلت منطقة كشمير القريبة من جبال الهيمالايا محل نزاع بين الهند وباكستان. الجنة الملعونة: دموع الفقراء في كشمير لماذا يلجأ الناس إلى أضرحة الصوفيين في \"كشمير الهندية\"؟ بالصور: الطفولة المسروقة في كشمير فمنذ تقسيم الهند وقيام باكستان عام 1947 وقعت حربان بين البلدين حول منطقة كشمير ذات الأغلبية المسلمة والتي يطالب البلدان بالسيادة عليها. وتعد كشمير اليوم واحدة من أكثر المناطق المدججة بالسلاح في العالم، في ما تدير الصين أجزاء من الإقليم. تسلسل زمني لأهم الأحداث في كشمير

Summary:
قالت الشرطة في القطاع الهندي من إقليم كشمير إن انفجار قنبلة أدى إلى مقتل 40 عنصرا على الأقل من قوات الأمن الخميس، بعد يوم من انفجار أدى لإصابة 12 تلميذا على الأقل.

Example 3:
Passage:
قبل المؤتمر العام الوطني الليبي الاستقالة وقبل المؤتمر العام الوطني (البرلمان الليبي) الاستقالة في جلسة عقدت الأحد. كانت المواجهات وقعت عندما تجمع متظاهرون أمام مقر كتيبة درع ليبيا في المدينة مطالبين بحظر المليشيات. وتحاول الحكومة الليبية منذ سقوط القذافي الحد من نفوذ المليشيات المتزايد، ونزع سلاحها ودمجها بالجيش النظامي. بيد أن الحكومة الليبية التي تواجه صعوبات في تشكيل جيش وشرطة محترفين، تلجأ بانتظام إلى الاعتماد على مليشيات الثوار السابقين لتأمين حدودها أو فض نزاعات قبلية. مواضيع قد تهمك نهاية وفي تشرين الأول/أكتوبر تظاهر سكان بنغازي احتجاجا على المليشيات وطردوا بعضها من قواعدها في المدينة.

Summary:
استقال رئيس الاركان الليبي يوسف المنقوش إثر مقتل 30 شخصا في مواجهات بين عناصر مليشيا مسلحة ومتظاهرين \"مناهضين للمليشيات\" في مدينة بنغازي الليبية.
'''
data['user_content'] = 'The passage you need to summarize\nPassage:\n' + data['text'] +'\nSummary:'

data2 = data
data = data[['system_message','user_content']]

In [ ]:
data.to_excel('SA-FewShot-gpt.xlsx')

In [ ]:
# Convert to JSON String
data = data.to_json(orient='records')

# parse JSON string and convert it into a list of python dictionaries
datadict = json.loads(data)

## Format Prompt

In [ ]:
# format dict into shape for fine tuning
few_shot_data = format_prompt(datadict)

# Save as jsonl
convert_to_jsonl_and_save(few_shot_data, 'SA-FewShot.jsonl')

✅ Data successfully written to SA-FewShot.jsonl

## Predict

In [ ]:
y_true = data2['summary'].values

In [ ]:
fs = pd.DataFrame()

fs['text'] = data2['text']
fs['summary'] = y_true
fs = fs.reset_index(drop=True)
fs.head()

,text,summary
0,واستحوذت القصة على نقاشات رواد مواقع التواصل ا...,أثار مقطع فيديو يظهر طفلا يقود سيارة ويعتدي لف...
1,وسيوفر البرنامج خمسة كيلوغرامات من الحبوب الرخ...,دشنت الحكومة الهندية برنامجا ضخما لتوفير الغذا...
2,كان ديفيد سورنسن يعمل كاتب خطابات في البيت الأ...,أصبح ديفيد سورنسن، كاتب الخطابات في البيت الأب...
3,ظهرت أعراض اصابات متوسطة في الدماغ وفقدان سمع ...,تعرض العاملون في السفارة الأمريكية في كوبا إلى...
4,وانطلق نقاش محتدم حول الصورة بعد أن نشرها الأم...,استأثرت صورة امرأة في صفوف الحرس الملكي السعود...

In [ ]:
store_predictions(fs, model, few_shot_data)

fine tuned model id is : gpt-4o-2024-08-06

In [ ]:
pred_few = pd.read_csv('TextSummarization-GPT4o-FewShot-predictions.csv')

In [ ]:
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import sacrebleu
import evaluate
from transformers import AutoTokenizer

# Initialize storage
bleu_scores = []
bleu_scores2 = []
rougeL_p = []
rougeL_r = []
rougeL_f = []
bertscore_p = []
bertscore_r = []
bertscore_f = []

# Initialize scorer
model_name = 'aubmindlab/bert-base-arabertv2'
tokenizer = AutoTokenizer.from_pretrained(model_name)
rouge = rouge_scorer.RougeScorer(['rougeL'], tokenizer=tokenizer)

# Iterate through rows
for _, row in pred_few.iterrows():
    raw_references = [row['summary']]  # One reference as list of strings
    raw_predictions = [row['Prediction']]  # One prediction

    # Normalize Arabic
    hyp = [normalize_arabic(text) for text in raw_predictions]
    ref = [[normalize_arabic(ref) for ref in raw_references]]  # Nested list for multiple refs per prediction

    # BLEU
    bleu = sacrebleu.corpus_bleu(hyp, ref)
    bleu_scores.append(bleu.score)

    bleu2 = evaluate.load("bleu")
    results = bleu2.compute(predictions= hyp, references= ref)
    bleu_scores2.append(results['bleu'])

    # ROUGE-L
    r_scores = rouge.score(row['summary'], row['Prediction'])
    rougeL_p.append(r_scores['rougeL'].precision)
    rougeL_r.append(r_scores['rougeL'].recall)
    rougeL_f.append(r_scores['rougeL'].fmeasure)

# BERTScore
P, R, F = bert_score(pred_few['Prediction'].tolist(), pred_few['summary'].tolist(), lang="ar", model_type="bert-base-multilingual-cased", verbose=False)
bertscore_p = P.tolist()
bertscore_r = R.tolist()
bertscore_f = F.tolist()

# Create summary DataFrame
metrics_df = pd.DataFrame({
    "BLEU1": bleu_scores,
    "BLEU2": bleu_scores2,
    "ROUGE_L_P": rougeL_p,
    "ROUGE_L_R": rougeL_r,
    "ROUGE_L_F": rougeL_f,
    "BERT_P": bertscore_p,
    "BERT_R": bertscore_r,
    "BERT_F": bertscore_f,
})

# Calculate min, max, mean
summary_stats = metrics_df.agg(['min', 'max', 'mean'])

print(summary_stats)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

          BLEU1     BLEU2  ROUGE_L_P  ROUGE_L_R  ROUGE_L_F    BERT_P  \
min    0.000000  0.000000   0.032258   0.095238   0.048193  0.561883
max   24.037659  0.240377   0.431034   0.589744   0.450980  0.789234
mean   3.506085  0.011535   0.154466   0.257180   0.188269  0.698273

        BERT_R    BERT_F
min   0.628667  0.593402
max   0.858650  0.820413
mean  0.731463  0.714170

# CoT

## Prepare Prompt

In [ ]:
data['system_message'] = '''You are provided with a detailed Arabic passage. Your task is to carefully read and comprehend the content, then generate a concise and coherent summary in one or two sentences that accurately captures the main ideas and key points.

Step 1: Comprehend the Passage
Thoroughly read the Arabic text to understand its main theme, event, or subject matter. Focus on grasping the overall context and intent of the passage.

Step 2: Extract Key Information
Identify the most important facts, ideas, or arguments presented. Disregard minor or repetitive details and focus on what’s essential to the overall message.

Step 3: Generate the Summary
Using the key points identified, write a clear and concise summary in one or two sentences. Ensure your summary is coherent, reflects the passage accurately, and avoids adding any personal interpretation.

Example 1:
Passage:
وكان الرئيس الأوكراني المؤقت، الكسندر تورتشينوف، قد أمر بسحب جميع القوات الأوكرانية من القرم. وسيطرت قوات روسية صباح الاثنين على قاعدة بحرية أوكرانية في فيودوسيا، في ثالث هجوم من نوعه خلال 48 ساعة، وذلك بحسب تصريحات مسؤولين أوكرانيين لبي بي سي . وقال المتحدث باسم وزارة الدفاع الأوكرانية فلاديسلاف سيليزنيوف إن القوات الروسية هاجمت القاعدة وألقت القبض على الجنود الأوكرانيين في قاعدة فيودوسيا وقيدت أيادي ضباطهم. ومن المتوقع أن تسيطر الأزمة الأوكرانية على قمة مجموعة الدول الصناعية السبع في لاهاي. مواضيع قد تهمك نهاية وأكد الرئيس الأمريكي باراك أوباما خلال لقاء مع نظيره الصيني شى جين بينغ على أن \"واشنطن وبكين يمكنهما، بالعمل سويا، تعزيز القانون الدولي واحترام سيادة الدول\". وتسيطر قوات روسية حاليا على معظم القواعد العسكرية الأوكرانية في القرم التي أعلنت موسكو ضمها للاتحاد الروسي بعد استفتاء أجرته السلطات المحلية هناك. قلق بالغ وقال مارك لوين، مراسل بي بي سي في القرم، إن القوات الروسية تسيطر بشكل كامل على القاعدة، ونقلت الجنود الأوكرانيين بعيدا إلى مكان مجهول. وتعد قاعدة فيودوسيا واحدة من آخر القواعد العسكرية التي بقيت تحت سيطرة كييف، لكن قوات روسية ظلت تحاصرها لبعض الوقت، حسبما أفاد مراسلنا. واقتحمت القوات الروسية قاعدتين أخريين وسيطرت عليهما يوم الجمعة. وكان مسؤولون عسكريون روس أعلنوا في وقت سابق أن العلم الروسي أصبح يرفرف على 189 وحدة ومنشأة عسكرية أوكرانية في القرم. وقال ديفيد ستيرن مراسل بي بي سي في كييف إن الأوكرانيين يتابعون هذه التطورات بقلق بالغ. وأشار إلى أن السؤال الذي يدور الآن هو ماذا سيكون رد فعل أوكرانيا والغرب وما هي الخطوة الروسية المقبلة. وحذر قائد الناتو في أوروبا يوم الأحد من أن القوات الروسية المنتشرة على الحدود الشرقية لأوكرانيا قادرة على شن عملية تمتد حتى مولدوفا. قمة الدول الصناعية الكبرى أوباما: العقوبات الغربية على موسكو ستؤثر على الاقتصاد الروسي. ويلقي ضم روسيا لمنطقة القرم بظلاله على قمة مجموعة السبع، التي كان مزمعا عقدها منذ فترة طويلة، بشأن تهديدات الأمن النووي. ومن المتوقع أن يبحث زعماء المجموعة موقفا موحدا حيال الأزمة. وأكد الرئيس الأمريكي على أن أوروبا والولايات المتحدة متفقون على دعم الحكومة الأوكرانية وشعبها، مشيرا إلى أن العقوبات التي فرضت على موسكو ستؤثر على الاقتصاد الروسي. ومن المقرر أن يلتقي وزير الخارجية الأمريكي، جون كيري، مع نظيره الروسي، سيرغي لافروف، على هامش قمة مجموعة السبع. انقطاع الكهرباء من جهة أخرى، شكا سكان محليون في بعض مناطق القرم من انقطاع الكهرباء في وقت متأخر من الأحد. ولف الظلام العديد من المدن من بينها بعض أحياء العاصمة سيمفربول. وقالت شركة توريد الكهرباء في القرم \"كريمنيرغو\" في بيان بث على موقعها الإلكتروني إن عطلا فنيا أصاب أحد الخطوط التي تديرها شركة الكهرباء الوطنية الأوكرانية \"اوكرينيرغو\". ولم يتسن الحصول على تعليق من اوكرينيرغو، ولم يصدر أيضا تأكيد مستقل حول سبب انقطاع الكهرباء. ضم القرم وضمت روسيا القرم إليها عقب استفتاء أجري في المنطقة في 16 مارس/آذار. وجاءت الخطوة الروسية بعد أن أطاحت احتجاجات بالرئيس الأوكراني السابق الموالي لروسيا فيكتور يانوكوفيتش. وأكدت روسيا أنها تحركت لحماية مواطني القرم المتحدرين من أصول روسية ضد من وصفتهم \"بالفاشيين\" الذين انتقلوا إليها من البلد الأم أوكرانيا. وردت الولايات المتحدة والاتحاد الأوروبي بفرض سلسلة من العقوبات ضد أفراد من بينهم مسؤولون بارزون اتهمتهم واشنطن وبروكسل بلعب دور في ضم القرم. موالون لروسيا يتظاهرون في مدينة مدينة دونيتسك، شرقي أوكرانيا. تسيطر قوات روسية حاليا على معظم القواعد العسكرية الأوكرانية في القرم.

Thoughts:
- Main Content: The passage discusses the ongoing crisis between Ukraine and Russia following Russia's annexation of Crimea in March 2014. It details military developments, international diplomatic responses, and the humanitarian situation in Crimea, including power outages.
- Key Information: The Ukrainian interim president ordered the withdrawal of troops from Crimea. Russian forces seized a Ukrainian naval base in Feodosia—third such seizure in 48 hours. The U.S. and allies are discussing unified responses at the G7 summit. NATO warned of a possible Russian advance into Moldova. Crimea is now largely controlled by Russian military forces after a disputed referendum. There are civilian hardships in Crimea, including widespread power outages. The annexation has led to Western sanctions on Russia. Political unrest continues in eastern Ukraine (e.g., Donetsk protests).

Summary:
بدأت القوات الأوكرانية الانسحاب من شبه جزيرة القرم.

Example 2:
Passage:
وذكرت وكالة الأنباء المحلية (جي.إن.إس) أن جماعة \"جيش محمد\" المتشددة أعلنت مسؤوليتها عن الهجوم. لكن ما هي منطقة كشمير المتنازع عليها بين الهند وباكستان؟ خلال العقود الست الماضية ظلت منطقة كشمير القريبة من جبال الهيمالايا محل نزاع بين الهند وباكستان. الجنة الملعونة: دموع الفقراء في كشمير لماذا يلجأ الناس إلى أضرحة الصوفيين في \"كشمير الهندية\"؟ بالصور: الطفولة المسروقة في كشمير فمنذ تقسيم الهند وقيام باكستان عام 1947 وقعت حربان بين البلدين حول منطقة كشمير ذات الأغلبية المسلمة والتي يطالب البلدان بالسيادة عليها. وتعد كشمير اليوم واحدة من أكثر المناطق المدججة بالسلاح في العالم، في ما تدير الصين أجزاء من الإقليم. تسلسل زمني لأهم الأحداث في كشمير

Thoughts:
- Main Content: The passage discusses a recent attack claimed by the militant group Jaish-e-Mohammed and provides background on the long-standing dispute over the Kashmir region, which has been a source of conflict between India and Pakistan since 1947.
- Key Information: The militant group Jaish-e-Mohammed claimed responsibility for a recent attack. Kashmir is a historically disputed region between India and Pakistan since 1947. Two wars have been fought over it, and the region has a Muslim majority population. China also controls part of the territory. Kashmir is now one of the most heavily militarized regions in the world. The passage references emotional, religious, and humanitarian issues in the area (e.g., poverty, shrine visits, stolen childhoods).

Summary:
قالت الشرطة في القطاع الهندي من إقليم كشمير إن انفجار قنبلة أدى إلى مقتل 40 عنصرا على الأقل من قوات الأمن الخميس، بعد يوم من انفجار أدى لإصابة 12 تلميذا على الأقل.

Example 3:
Passage:
قبل المؤتمر العام الوطني الليبي الاستقالة وقبل المؤتمر العام الوطني (البرلمان الليبي) الاستقالة في جلسة عقدت الأحد. كانت المواجهات وقعت عندما تجمع متظاهرون أمام مقر كتيبة درع ليبيا في المدينة مطالبين بحظر المليشيات. وتحاول الحكومة الليبية منذ سقوط القذافي الحد من نفوذ المليشيات المتزايد، ونزع سلاحها ودمجها بالجيش النظامي. بيد أن الحكومة الليبية التي تواجه صعوبات في تشكيل جيش وشرطة محترفين، تلجأ بانتظام إلى الاعتماد على مليشيات الثوار السابقين لتأمين حدودها أو فض نزاعات قبلية. مواضيع قد تهمك نهاية وفي تشرين الأول/أكتوبر تظاهر سكان بنغازي احتجاجا على المليشيات وطردوا بعضها من قواعدها في المدينة.

Thoughts:
- Main Content: The passage outlines the complex security situation in post-Gaddafi Libya, particularly in Benghazi, highlighting public protests against militias, the role of former rebel groups, and the government's challenges in establishing professional security forces.
- Key Information: The Libyan General National Congress accepted a resignation in a session held on Sunday. Protests erupted in Benghazi demanding the dissolution of militias, particularly targeting the Libya Shield Brigade. Since the fall of Gaddafi, the government has struggled to disarm militias and integrate them into the regular army. Due to weak formal security institutions, the government often relies on these same militias for tasks like border security and conflict resolution. In October, Benghazi residents protested and expelled some militias from their bases.

Summary:
استقال رئيس الاركان الليبي يوسف المنقوش إثر مقتل 30 شخصا في مواجهات بين عناصر مليشيا مسلحة ومتظاهرين \"مناهضين للمليشيات\" في مدينة بنغازي الليبية.
'''
data['user_content'] = 'The passage you need to summarize\nPassage:\n' + data['text']

data2 = data
data = data[['system_message','user_content']]

In [ ]:
data.to_excel('SA-CoT-gpt.xlsx')

In [ ]:
# Convert to JSON String
data = data.to_json(orient='records')

# parse JSON string and convert it into a list of python dictionaries
datadict = json.loads(data)

## Format Prompt

In [ ]:
# format dict into shape for fine tuning
CoT_data = format_prompt(datadict)

# Save as jsonl
convert_to_jsonl_and_save(CoT_data, 'SA-CoT.jsonl')

✅ Data successfully written to SA-CoT.jsonl

## Predict

In [ ]:
def predict(test, model):
  response = client.chat.completions.create(
      model = model,
      messages= test,
      temperature = 0.2,
      max_tokens= 512
  )
  return response.choices[0].message.content

In [ ]:
def store_predictions(test_df, model, test_data):
  print("fine tuned model id is :", model)
  test_df['Prediction']= None

  for index, row in test_df.iterrows():
    test_message = test_data[index]['messages']
    prediction_result = predict(test_message, model)
    test_df.at[index, 'Prediction'] = prediction_result

  test_df.to_csv("Text Summarization-GPT4o-CoT-predictions.csv")

In [ ]:
y_true = data2['summary'].values

In [ ]:
cot = pd.DataFrame()

cot['text'] = data2['text']
cot['summary'] = y_true
cot = cot.reset_index(drop=True)
cot.head()

,text,summary
0,واستحوذت القصة على نقاشات رواد مواقع التواصل ا...,أثار مقطع فيديو يظهر طفلا يقود سيارة ويعتدي لف...
1,وسيوفر البرنامج خمسة كيلوغرامات من الحبوب الرخ...,دشنت الحكومة الهندية برنامجا ضخما لتوفير الغذا...
2,كان ديفيد سورنسن يعمل كاتب خطابات في البيت الأ...,أصبح ديفيد سورنسن، كاتب الخطابات في البيت الأب...
3,ظهرت أعراض اصابات متوسطة في الدماغ وفقدان سمع ...,تعرض العاملون في السفارة الأمريكية في كوبا إلى...
4,وانطلق نقاش محتدم حول الصورة بعد أن نشرها الأم...,استأثرت صورة امرأة في صفوف الحرس الملكي السعود...

In [ ]:
store_predictions(cot, model, CoT_data)

fine tuned model id is : gpt-4o-2024-08-06

In [ ]:
pred_cot = pd.read_csv('TextSummarization-GPT4o-CoT-predictions.csv')

In [ ]:
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import sacrebleu
import evaluate
from transformers import AutoTokenizer

# Initialize storage
bleu_scores = []
bleu_scores2 = []
rougeL_p = []
rougeL_r = []
rougeL_f = []
bertscore_p = []
bertscore_r = []
bertscore_f = []

# Initialize scorer
model_name = 'aubmindlab/bert-base-arabertv2'
tokenizer = AutoTokenizer.from_pretrained(model_name)
rouge = rouge_scorer.RougeScorer(['rougeL'], tokenizer=tokenizer)

# Iterate through rows
for _, row in pred_cot.iterrows():
    raw_references = [row['summary']]  # One reference as list of strings
    raw_predictions = [row['Prediction']]  # One prediction

    # Normalize Arabic
    hyp = [normalize_arabic(text) for text in raw_predictions]
    ref = [[normalize_arabic(ref) for ref in raw_references]]  # Nested list for multiple refs per prediction

    # BLEU
    bleu = sacrebleu.corpus_bleu(hyp, ref)
    bleu_scores.append(bleu.score)

    bleu2 = evaluate.load("bleu")
    results = bleu2.compute(predictions= hyp, references= ref)
    bleu_scores2.append(results['bleu'])

    # ROUGE-L
    r_scores = rouge.score(row['summary'], row['Prediction'])
    rougeL_p.append(r_scores['rougeL'].precision)
    rougeL_r.append(r_scores['rougeL'].recall)
    rougeL_f.append(r_scores['rougeL'].fmeasure)

# BERTScore
P, R, F = bert_score(pred_cot['Prediction'].tolist(), pred_cot['summary'].tolist(), lang="ar", model_type="bert-base-multilingual-cased", verbose=False)
bertscore_p = P.tolist()
bertscore_r = R.tolist()
bertscore_f = F.tolist()

# Create summary DataFrame
metrics_df = pd.DataFrame({
    "BLEU1": bleu_scores,
    "BLEU2": bleu_scores2,
    "ROUGE_L_P": rougeL_p,
    "ROUGE_L_R": rougeL_r,
    "ROUGE_L_F": rougeL_f,
    "BERT_P": bertscore_p,
    "BERT_R": bertscore_r,
    "BERT_F": bertscore_f,
})

# Calculate min, max, mean
summary_stats = metrics_df.agg(['min', 'max', 'mean'])

print(summary_stats)

          BLEU1     BLEU2  ROUGE_L_P  ROUGE_L_R  ROUGE_L_F    BERT_P  \
min    0.000000  0.000000   0.000000   0.000000   0.000000  0.528827
max   25.474299  0.254743   0.360000   0.600000   0.446602  0.787956
mean   2.657251  0.010084   0.105898   0.252551   0.136483  0.655012

        BERT_R    BERT_F
min   0.553222  0.567216
max   0.860556  0.814876
mean  0.709921  0.680484